import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster"
import { Inter } from "next/font/google";
import { ClerkProvider, SignIn, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex justify-between w-full bg-purple-300 p-5">
            <Link href='/'>
              <h1 className="text-xl font-bold">MasterP</h1>
            </Link>
            <UserButton showName />
          </header>
          <SignedOut>
          <div className="flex-grow flex justify-center items-center h-sceeen w-full h-screen">
              <SignIn routing='hash'/>
            </div>
          </SignedOut>
          <SignedIn>
            {children}
            <Toaster />
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
